### ISSUE TITLE
Qr code With Random Number

### ISSUE THREAD

**Issue by Pankaj91580** [t0k4rt/phpqrcode#34]
I want To Generate Qr Code with Random Number when i click the generate Qrcode.
And ThaRcode should be unique Every time.

**Comment by budwig** [comment]
Only way to achieve that is to store the results in a database and verify the new codes against the older ones.

**Comment by t0k4rt** [comment]
The above solution is  a good solution if you want to be really sure every id ar unique.

But you can also generate an uuid v4, chances are high for the id to be unique.

see:
https://github.com/ramsey/uuid
