### ISSUE TITLE
Including string in final QR code EPS

### ISSUE THREAD

**Issue by Sijan117** [t0k4rt/phpqrcode#36]
Trying to export the QR code in EPS format with the encoded string in plain text directly below it, to make a label of sorts. 

Been meddling around with the code to try and understand the process and see where I can inject this step but I'm not getting far. 

Is this even possible or am I asking too much?

**Comment by t0k4rt** [comment]
I think this should be possible if you tinker with vectEPS function in qrvect.php (around line 132).
You should be able to add postscript code like:

    /Times-Roman findfont
    20 scalefont
    setfont
    newpath
    200 200 moveto % as the name says, move the cursor to x y
    (Hello world !) show

This should write text dirctely in you eps file et should show text over (I'm not 100% sure) the qr code.

If you manage to have something working, I would be interested in seing what it will look like for the sake of curiosity :-)
