### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [t0k4rt/phpqrcode#49]
As title, I find this project via GitHub repository search.

It looks good, but it seems this project has been inactive for whiles.

I wonder this project is still maintained?

**Comment by kanine** [comment]
This one seems to be currently maintained, though I haven't used it (yet).

https://github.com/chillerlan/php-qrcode

**Comment by peter279k** [comment]
Thanks for @kanine, I will look at this PHP package you mention :).
